// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StandApi.Models;
using System;

namespace StandApi.Migrations
{
    [DbContext(typeof(StandContext))]
    [Migration("20180528071224_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("StandApi.Models.Stand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Stands");
                });

            modelBuilder.Entity("StandApi.Models.StandEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Error");

                    b.Property<int>("StandID");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.HasIndex("StandID");

                    b.ToTable("StandEntries");
                });

            modelBuilder.Entity("StandApi.Models.StandEntry", b =>
                {
                    b.HasOne("StandApi.Models.Stand", "Stand")
                        .WithMany("Items")
                        .HasForeignKey("StandID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
